# Estuary API
#
# This is the API for the Estuary application.
#
# OpenAPI spec version: 0.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ContentAddBody Class
#'
#' @field file 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ContentAddBody <- R6::R6Class(
  'ContentAddBody',
  public = list(
    `file` = NULL,
    initialize = function(`file`){
      if (!missing(`file`)) {
        stopifnot(is.character(`file`), length(`file`) == 1)
        self$`file` <- `file`
      }
    },
    toJSON = function() {
      ContentAddBodyObject <- list()
      if (!is.null(self$`file`)) {
        ContentAddBodyObject[['file']] <- self$`file`
      }

      ContentAddBodyObject
    },
    fromJSON = function(ContentAddBodyJson) {
      ContentAddBodyObject <- jsonlite::fromJSON(ContentAddBodyJson)
      if (!is.null(ContentAddBodyObject$`file`)) {
        self$`file` <- ContentAddBodyObject$`file`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "file": %s
        }',
        self$`file`
      )
    },
    fromJSONString = function(ContentAddBodyJson) {
      ContentAddBodyObject <- jsonlite::fromJSON(ContentAddBodyJson)
      self$`file` <- ContentAddBodyObject$`file`
    }
  )
)
