/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MainGetApiKeysResp model module.
 * @module model/MainGetApiKeysResp
 * @version 0.0.0
 */
export class MainGetApiKeysResp {
  /**
   * Constructs a new <code>MainGetApiKeysResp</code>.
   * @alias module:model/MainGetApiKeysResp
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MainGetApiKeysResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MainGetApiKeysResp} obj Optional instance to populate.
   * @return {module:model/MainGetApiKeysResp} The populated <code>MainGetApiKeysResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MainGetApiKeysResp();
      if (data.hasOwnProperty('expiry'))
        obj.expiry = ApiClient.convertToType(data['expiry'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} expiry
 */
MainGetApiKeysResp.prototype.expiry = undefined;

/**
 * @member {String} token
 */
MainGetApiKeysResp.prototype.token = undefined;

