/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MainUserStatsResponse model module.
 * @module model/MainUserStatsResponse
 * @version 0.0.0
 */
export class MainUserStatsResponse {
  /**
   * Constructs a new <code>MainUserStatsResponse</code>.
   * @alias module:model/MainUserStatsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MainUserStatsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MainUserStatsResponse} obj Optional instance to populate.
   * @return {module:model/MainUserStatsResponse} The populated <code>MainUserStatsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MainUserStatsResponse();
      if (data.hasOwnProperty('numPins'))
        obj.numPins = ApiClient.convertToType(data['numPins'], 'Number');
      if (data.hasOwnProperty('totalSize'))
        obj.totalSize = ApiClient.convertToType(data['totalSize'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} numPins
 */
MainUserStatsResponse.prototype.numPins = undefined;

/**
 * @member {Number} totalSize
 */
MainUserStatsResponse.prototype.totalSize = undefined;

