/* tslint:disable */
/* eslint-disable */
/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MainCollection
 */
export interface MainCollection {
    /**
     * 
     * @type {string}
     * @memberof MainCollection
     */
    cid?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCollection
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCollection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCollection
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof MainCollection
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof MainCollection
     */
    uuid?: string;
}
