/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EstuaryApi);
  }
}(this, function(expect, EstuaryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EstuaryApi.ContentApi();
  });

  describe('(package)', function() {
    describe('ContentApi', function() {
      describe('contentAddCarPost', function() {
        it('should call contentAddCarPost successfully', function(done) {
          // TODO: uncomment, update parameter values for contentAddCarPost call
          /*
          var opts = {};

          instance.contentAddCarPost(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentAddIpfsPost', function() {
        it('should call contentAddIpfsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for contentAddIpfsPost call
          /*

          instance.contentAddIpfsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentAddPost', function() {
        it('should call contentAddPost successfully', function(done) {
          // TODO: uncomment, update parameter values for contentAddPost call and complete the assertions
          /*

          instance.contentAddPost(file, coluuid, dir, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EstuaryApi.UtilContentAddResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentAggregatedContentGet', function() {
        it('should call contentAggregatedContentGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentAggregatedContentGet call and complete the assertions
          /*

          instance.contentAggregatedContentGet(content, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentAllDealsGet', function() {
        it('should call contentAllDealsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentAllDealsGet call
          /*

          instance.contentAllDealsGet(begin, duration, all, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentBwUsageContentGet', function() {
        it('should call contentBwUsageContentGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentBwUsageContentGet call
          /*

          instance.contentBwUsageContentGet(content, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentCreatePost', function() {
        it('should call contentCreatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for contentCreatePost call
          /*

          instance.contentCreatePost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentDealsGet', function() {
        it('should call contentDealsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentDealsGet call
          /*
          var opts = {};

          instance.contentDealsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentEnsureReplicationDatacidGet', function() {
        it('should call contentEnsureReplicationDatacidGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentEnsureReplicationDatacidGet call
          /*

          instance.contentEnsureReplicationDatacidGet(datacid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentFailuresContentGet', function() {
        it('should call contentFailuresContentGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentFailuresContentGet call and complete the assertions
          /*

          instance.contentFailuresContentGet(content, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentImportdealPost', function() {
        it('should call contentImportdealPost successfully', function(done) {
          // TODO: uncomment, update parameter values for contentImportdealPost call
          /*

          instance.contentImportdealPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentListGet', function() {
        it('should call contentListGet successfully', function(done) {
          // TODO: uncomment contentListGet call and complete the assertions
          /*

          instance.contentListGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(&#x27;string&#x27;);
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentReadContGet', function() {
        it('should call contentReadContGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentReadContGet call
          /*

          instance.contentReadContGet(cont, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentStagingZonesGet', function() {
        it('should call contentStagingZonesGet successfully', function(done) {
          // TODO: uncomment contentStagingZonesGet call
          /*

          instance.contentStagingZonesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentStatsGet', function() {
        it('should call contentStatsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentStatsGet call
          /*

          instance.contentStatsGet(limit, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('contentStatusIdGet', function() {
        it('should call contentStatusIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for contentStatusIdGet call
          /*

          instance.contentStatusIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
