/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.MainEstimateDealBody;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-09-27T20:41:13.008650-10:00[Pacific/Honolulu]")
@Validated
public interface DealApi {

    @Operation(summary = "Estimate the cost of a deal", description = "This endpoint estimates the cost of a deal", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/estimate",
        consumes = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> dealEstimatePost(@Parameter(in = ParameterIn.DEFAULT, description = "The size of the deal in bytes, the replication factor, and the duration of the deal in blocks", required=true, schema=@Schema()) @Valid @RequestBody MainEstimateDealBody body);


    @Operation(summary = "Get Deal Info", description = "This endpoint returns the deal info for a deal", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/info/{dealid}",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealInfoDealidGet(@Parameter(in = ParameterIn.PATH, description = "Deal ID", required=true, schema=@Schema()) @PathVariable("dealid") Integer dealid);


    @Operation(summary = "Get Proposal", description = "This endpoint returns the proposal for a deal", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/proposal/{propcid}",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealProposalPropcidGet(@Parameter(in = ParameterIn.PATH, description = "Proposal CID", required=true, schema=@Schema()) @PathVariable("propcid") String propcid);


    @Operation(summary = "Query Ask", description = "This endpoint returns the ask for a given CID", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/query/{miner}",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealQueryMinerGet(@Parameter(in = ParameterIn.PATH, description = "CID", required=true, schema=@Schema()) @PathVariable("miner") String miner);


    @Operation(summary = "Get Deal Status by PropCid", description = "Get Deal Status by PropCid", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/status-by-proposal/{propcid}",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealStatusByProposalPropcidGet(@Parameter(in = ParameterIn.PATH, description = "PropCid", required=true, schema=@Schema()) @PathVariable("propcid") String propcid);


    @Operation(summary = "Deal Status", description = "This endpoint returns the status of a deal", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/status/{miner}/{propcid}",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealStatusMinerPropcidGet(@Parameter(in = ParameterIn.PATH, description = "Miner", required=true, schema=@Schema()) @PathVariable("miner") String miner, @Parameter(in = ParameterIn.PATH, description = "Proposal CID", required=true, schema=@Schema()) @PathVariable("propcid") String propcid);


    @Operation(summary = "Transfer In Progress", description = "This endpoint returns the in-progress transfers", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/transfer/in-progress",
        method = RequestMethod.GET)
    ResponseEntity<Void> dealTransferInProgressGet();


    @Operation(summary = "Transfer Status", description = "This endpoint returns the status of a transfer", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "deals" })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/deal/transfer/status",
        method = RequestMethod.POST)
    ResponseEntity<Void> dealTransferStatusPost();

}

