/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AutoretrieveApiController : ControllerBase
    { 
        /// <summary>
        /// Register autoretrieve server
        /// </summary>
        /// <remarks>This endpoint registers a new autoretrieve server</remarks>
        /// <param name="body">Autoretrieve&#x27;s public key</param>
        [HttpPost]
        [Route("//api.estuary.tech//admin/autoretrieve/init")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AdminAutoretrieveInitPost")]
        public virtual IActionResult AdminAutoretrieveInitPost([FromBody]string body)
        { 
            throw new NotImplementedException();
        }

        /// <summary>
        /// List autoretrieve servers
        /// </summary>
        /// <remarks>This endpoint lists all registered autoretrieve servers</remarks>
        [HttpGet]
        [Route("//api.estuary.tech//admin/autoretrieve/list")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AdminAutoretrieveListGet")]
        public virtual IActionResult AdminAutoretrieveListGet()
        { 
            throw new NotImplementedException();
        }

        /// <summary>
        /// Marks autoretrieve server as up
        /// </summary>
        /// <remarks>This endpoint updates the lastConnection field for autoretrieve</remarks>
        /// <param name="token">Autoretrieve&#x27;s auth token</param>
        [HttpPost]
        [Route("//api.estuary.tech//autoretrieve/heartbeat")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AutoretrieveHeartbeatPost")]
        public virtual IActionResult AutoretrieveHeartbeatPost([FromHeader][Required()]string token)
        { 
            throw new NotImplementedException();
        }
    }
}
