/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AdminApi", () => {
  let instance: api.AdminApi
  beforeEach(function() {
    instance = new api.AdminApi(config)
  });

  test("adminPeeringPeersDelete", () => {
    return expect(instance.adminPeeringPeersDelete({})).resolves.toBe(null)
  })
  test("adminPeeringPeersGet", () => {
    return expect(instance.adminPeeringPeersGet({})).resolves.toBe(null)
  })
  test("adminPeeringPeersPost", () => {
    return expect(instance.adminPeeringPeersPost({})).resolves.toBe(null)
  })
  test("adminPeeringStartPost", () => {
    return expect(instance.adminPeeringStartPost({})).resolves.toBe(null)
  })
  test("adminPeeringStatusGet", () => {
    return expect(instance.adminPeeringStatusGet({})).resolves.toBe(null)
  })
  test("adminPeeringStopPost", () => {
    return expect(instance.adminPeeringStopPost({})).resolves.toBe(null)
  })
  test("adminSystemConfigGet", () => {
    return expect(instance.adminSystemConfigGet({})).resolves.toBe(null)
  })
  test("adminUsersGet", () => {
    return expect(instance.adminUsersGet({})).resolves.toBe(null)
  })
})

describe("AutoretrieveApi", () => {
  let instance: api.AutoretrieveApi
  beforeEach(function() {
    instance = new api.AutoretrieveApi(config)
  });

  test("adminAutoretrieveInitPost", () => {
    const body: string = undefined
    return expect(instance.adminAutoretrieveInitPost(body, {})).resolves.toBe(null)
  })
  test("adminAutoretrieveListGet", () => {
    return expect(instance.adminAutoretrieveListGet({})).resolves.toBe(null)
  })
  test("autoretrieveHeartbeatPost", () => {
    const token: string = "token_example"
    return expect(instance.autoretrieveHeartbeatPost(token, {})).resolves.toBe(null)
  })
})

describe("CollectionsApi", () => {
  let instance: api.CollectionsApi
  beforeEach(function() {
    instance = new api.CollectionsApi(config)
  });

  test("collectionsColuuidCommitPost", () => {
    const coluuid: string = "coluuid_example"
    return expect(instance.collectionsColuuidCommitPost(coluuid, {})).resolves.toBe(null)
  })
  test("collectionsColuuidDelete", () => {
    const coluuid: string = "coluuid_example"
    return expect(instance.collectionsColuuidDelete(coluuid, {})).resolves.toBe(null)
  })
  test("collectionsColuuidGet", () => {
    const coluuid: string = "coluuid_example"
    const dir: string = "dir_example"
    return expect(instance.collectionsColuuidGet(coluuid, dir, {})).resolves.toBe(null)
  })
  test("collectionsColuuidPost", () => {
    const body: Array<number> = undefined
    return expect(instance.collectionsColuuidPost(body, {})).resolves.toBe(null)
  })
  test("collectionsFsAddPost", () => {
    const coluuid: string = "coluuid_example"
    const content: string = "content_example"
    const path: string = "path_example"
    return expect(instance.collectionsFsAddPost(coluuid, content, path, {})).resolves.toBe(null)
  })
  test("collectionsGet", () => {
    const id: number = 56
    return expect(instance.collectionsGet(id, {})).resolves.toBe(null)
  })
  test("collectionsPost", () => {
    const body: api.MainCreateCollectionBody = undefined
    return expect(instance.collectionsPost(body, {})).resolves.toBe(null)
  })
})

describe("ContentApi", () => {
  let instance: api.ContentApi
  beforeEach(function() {
    instance = new api.ContentApi(config)
  });

  test("contentAddCarPost", () => {
    const body: string = undefined
    const filename: string = "filename_example"
    const commp: string = "commp_example"
    const size: string = "size_example"
    return expect(instance.contentAddCarPost(body, filename, commp, size, {})).resolves.toBe(null)
  })
  test("contentAddIpfsPost", () => {
    const body: api.UtilContentAddIpfsBody = undefined
    return expect(instance.contentAddIpfsPost(body, {})).resolves.toBe(null)
  })
  test("contentAddPost", () => {
    const file: Blob = "file_example"
    const coluuid: string = "coluuid_example"
    const dir: string = "dir_example"
    return expect(instance.contentAddPost(file, coluuid, dir, {})).resolves.toBe(null)
  })
  test("contentAggregatedContentGet", () => {
    const content: string = "content_example"
    return expect(instance.contentAggregatedContentGet(content, {})).resolves.toBe(null)
  })
  test("contentAllDealsGet", () => {
    const begin: string = "begin_example"
    const duration: string = "duration_example"
    const all: string = "all_example"
    return expect(instance.contentAllDealsGet(begin, duration, all, {})).resolves.toBe(null)
  })
  test("contentBwUsageContentGet", () => {
    const content: string = "content_example"
    return expect(instance.contentBwUsageContentGet(content, {})).resolves.toBe(null)
  })
  test("contentCreatePost", () => {
    const body: string = undefined
    return expect(instance.contentCreatePost(body, {})).resolves.toBe(null)
  })
  test("contentDealsGet", () => {
    const limit: number = 56
    const offset: number = 56
    return expect(instance.contentDealsGet(limit, offset, {})).resolves.toBe(null)
  })
  test("contentEnsureReplicationDatacidGet", () => {
    const datacid: string = "datacid_example"
    return expect(instance.contentEnsureReplicationDatacidGet(datacid, {})).resolves.toBe(null)
  })
  test("contentFailuresContentGet", () => {
    const content: string = "content_example"
    return expect(instance.contentFailuresContentGet(content, {})).resolves.toBe(null)
  })
  test("contentImportdealPost", () => {
    const body: api.MainImportDealBody = undefined
    return expect(instance.contentImportdealPost(body, {})).resolves.toBe(null)
  })
  test("contentListGet", () => {
    return expect(instance.contentListGet({})).resolves.toBe(null)
  })
  test("contentReadContGet", () => {
    const cont: string = "cont_example"
    return expect(instance.contentReadContGet(cont, {})).resolves.toBe(null)
  })
  test("contentStagingZonesGet", () => {
    return expect(instance.contentStagingZonesGet({})).resolves.toBe(null)
  })
  test("contentStatsGet", () => {
    const limit: string = "limit_example"
    return expect(instance.contentStatsGet(limit, {})).resolves.toBe(null)
  })
  test("contentStatusIdGet", () => {
    const id: number = 56
    return expect(instance.contentStatusIdGet(id, {})).resolves.toBe(null)
  })
})

describe("DealsApi", () => {
  let instance: api.DealsApi
  beforeEach(function() {
    instance = new api.DealsApi(config)
  });

  test("dealEstimatePost", () => {
    const body: api.MainEstimateDealBody = undefined
    return expect(instance.dealEstimatePost(body, {})).resolves.toBe(null)
  })
  test("dealInfoDealidGet", () => {
    const dealid: number = 56
    return expect(instance.dealInfoDealidGet(dealid, {})).resolves.toBe(null)
  })
  test("dealProposalPropcidGet", () => {
    const propcid: string = "propcid_example"
    return expect(instance.dealProposalPropcidGet(propcid, {})).resolves.toBe(null)
  })
  test("dealQueryMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.dealQueryMinerGet(miner, {})).resolves.toBe(null)
  })
  test("dealStatusByProposalPropcidGet", () => {
    const propcid: string = "propcid_example"
    return expect(instance.dealStatusByProposalPropcidGet(propcid, {})).resolves.toBe(null)
  })
  test("dealStatusMinerPropcidGet", () => {
    const miner: string = "miner_example"
    const propcid: string = "propcid_example"
    return expect(instance.dealStatusMinerPropcidGet(miner, propcid, {})).resolves.toBe(null)
  })
  test("dealTransferInProgressGet", () => {
    return expect(instance.dealTransferInProgressGet({})).resolves.toBe(null)
  })
  test("dealTransferStatusPost", () => {
    return expect(instance.dealTransferStatusPost({})).resolves.toBe(null)
  })
  test("dealsFailuresGet", () => {
    return expect(instance.dealsFailuresGet({})).resolves.toBe(null)
  })
  test("dealsMakeMinerPost", () => {
    const body: string = undefined
    const miner: string = "miner_example"
    return expect(instance.dealsMakeMinerPost(body, miner, {})).resolves.toBe(null)
  })
  test("dealsStatusDealGet", () => {
    const deal: number = 56
    return expect(instance.dealsStatusDealGet(deal, {})).resolves.toBe(null)
  })
  test("publicDealsFailuresGet", () => {
    return expect(instance.publicDealsFailuresGet({})).resolves.toBe(null)
  })
  test("publicMinersStorageQueryMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersStorageQueryMinerGet(miner, {})).resolves.toBe(null)
  })
})

describe("MetricsApi", () => {
  let instance: api.MetricsApi
  beforeEach(function() {
    instance = new api.MetricsApi(config)
  });

  test("publicMetricsDealsOnChainGet", () => {
    return expect(instance.publicMetricsDealsOnChainGet({})).resolves.toBe(null)
  })
})

describe("MinerApi", () => {
  let instance: api.MinerApi
  beforeEach(function() {
    instance = new api.MinerApi(config)
  });

  test("publicMinersDealsMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersDealsMinerGet(miner, {})).resolves.toBe(null)
  })
  test("publicMinersStatsMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersStatsMinerGet(miner, {})).resolves.toBe(null)
  })
})

describe("NetApi", () => {
  let instance: api.NetApi
  beforeEach(function() {
    instance = new api.NetApi(config)
  });

  test("netAddrsGet", () => {
    return expect(instance.netAddrsGet({})).resolves.toBe(null)
  })
  test("publicMinersFailuresMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersFailuresMinerGet(miner, {})).resolves.toBe(null)
  })
  test("publicMinersGet", () => {
    return expect(instance.publicMinersGet({})).resolves.toBe(null)
  })
  test("publicNetAddrsGet", () => {
    return expect(instance.publicNetAddrsGet({})).resolves.toBe(null)
  })
  test("publicNetPeersGet", () => {
    return expect(instance.publicNetPeersGet({})).resolves.toBe(null)
  })
})

describe("PeeringApi", () => {
  let instance: api.PeeringApi
  beforeEach(function() {
    instance = new api.PeeringApi(config)
  });

  test("adminPeeringPeersDelete", () => {
    return expect(instance.adminPeeringPeersDelete({})).resolves.toBe(null)
  })
  test("adminPeeringPeersGet", () => {
    return expect(instance.adminPeeringPeersGet({})).resolves.toBe(null)
  })
  test("adminPeeringPeersPost", () => {
    return expect(instance.adminPeeringPeersPost({})).resolves.toBe(null)
  })
  test("adminPeeringStartPost", () => {
    return expect(instance.adminPeeringStartPost({})).resolves.toBe(null)
  })
  test("adminPeeringStatusGet", () => {
    return expect(instance.adminPeeringStatusGet({})).resolves.toBe(null)
  })
  test("adminPeeringStopPost", () => {
    return expect(instance.adminPeeringStopPost({})).resolves.toBe(null)
  })
})

describe("PeersApi", () => {
  let instance: api.PeersApi
  beforeEach(function() {
    instance = new api.PeersApi(config)
  });

  test("adminPeeringPeersDelete", () => {
    return expect(instance.adminPeeringPeersDelete({})).resolves.toBe(null)
  })
  test("adminPeeringPeersGet", () => {
    return expect(instance.adminPeeringPeersGet({})).resolves.toBe(null)
  })
  test("adminPeeringPeersPost", () => {
    return expect(instance.adminPeeringPeersPost({})).resolves.toBe(null)
  })
  test("adminPeeringStartPost", () => {
    return expect(instance.adminPeeringStartPost({})).resolves.toBe(null)
  })
  test("adminPeeringStatusGet", () => {
    return expect(instance.adminPeeringStatusGet({})).resolves.toBe(null)
  })
  test("adminPeeringStopPost", () => {
    return expect(instance.adminPeeringStopPost({})).resolves.toBe(null)
  })
})

describe("PinningApi", () => {
  let instance: api.PinningApi
  beforeEach(function() {
    instance = new api.PinningApi(config)
  });

  test("pinningPinsGet", () => {
    return expect(instance.pinningPinsGet({})).resolves.toBe(null)
  })
  test("pinningPinsPinidDelete", () => {
    const pinid: string = "pinid_example"
    return expect(instance.pinningPinsPinidDelete(pinid, {})).resolves.toBe(null)
  })
  test("pinningPinsPinidGet", () => {
    const pinid: string = "pinid_example"
    return expect(instance.pinningPinsPinidGet(pinid, {})).resolves.toBe(null)
  })
  test("pinningPinsPinidPost", () => {
    const pinid: string = "pinid_example"
    return expect(instance.pinningPinsPinidPost(pinid, {})).resolves.toBe(null)
  })
  test("pinningPinsPost", () => {
    const cid: string = "cid_example"
    const name: string = "name_example"
    return expect(instance.pinningPinsPost(cid, name, {})).resolves.toBe(null)
  })
})

describe("PublicApi", () => {
  let instance: api.PublicApi
  beforeEach(function() {
    instance = new api.PublicApi(config)
  });

  test("publicByCidCidGet", () => {
    const cid: string = "cid_example"
    return expect(instance.publicByCidCidGet(cid, {})).resolves.toBe(null)
  })
  test("publicInfoGet", () => {
    return expect(instance.publicInfoGet({})).resolves.toBe(null)
  })
  test("publicMetricsDealsOnChainGet", () => {
    return expect(instance.publicMetricsDealsOnChainGet({})).resolves.toBe(null)
  })
  test("publicMinersDealsMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersDealsMinerGet(miner, {})).resolves.toBe(null)
  })
  test("publicMinersFailuresMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersFailuresMinerGet(miner, {})).resolves.toBe(null)
  })
  test("publicMinersGet", () => {
    return expect(instance.publicMinersGet({})).resolves.toBe(null)
  })
  test("publicMinersStatsMinerGet", () => {
    const miner: string = "miner_example"
    return expect(instance.publicMinersStatsMinerGet(miner, {})).resolves.toBe(null)
  })
  test("publicNetAddrsGet", () => {
    return expect(instance.publicNetAddrsGet({})).resolves.toBe(null)
  })
  test("publicNetPeersGet", () => {
    return expect(instance.publicNetPeersGet({})).resolves.toBe(null)
  })
  test("publicStatsGet", () => {
    return expect(instance.publicStatsGet({})).resolves.toBe(null)
  })
})

describe("UserApi", () => {
  let instance: api.UserApi
  beforeEach(function() {
    instance = new api.UserApi(config)
  });

  test("userApiKeysGet", () => {
    return expect(instance.userApiKeysGet({})).resolves.toBe(null)
  })
  test("userApiKeysKeyDelete", () => {
    const key: string = "key_example"
    return expect(instance.userApiKeysKeyDelete(key, {})).resolves.toBe(null)
  })
  test("userApiKeysPost", () => {
    return expect(instance.userApiKeysPost({})).resolves.toBe(null)
  })
  test("userExportGet", () => {
    return expect(instance.userExportGet({})).resolves.toBe(null)
  })
  test("userStatsGet", () => {
    return expect(instance.userStatsGet({})).resolves.toBe(null)
  })
})

