/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/application-research/estuary/master/docs/swagger.json/",
		Index,
	},

	Route{
		"AdminPeeringPeersDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersDelete,
	},

	Route{
		"AdminPeeringPeersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersGet,
	},

	Route{
		"AdminPeeringPeersPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersPost,
	},

	Route{
		"AdminPeeringStartPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/start",
		AdminPeeringStartPost,
	},

	Route{
		"AdminPeeringStatusGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/status",
		AdminPeeringStatusGet,
	},

	Route{
		"AdminPeeringStopPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/stop",
		AdminPeeringStopPost,
	},

	Route{
		"AdminSystemConfigGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/system/config",
		AdminSystemConfigGet,
	},

	Route{
		"AdminUsersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/users",
		AdminUsersGet,
	},

	Route{
		"AdminAutoretrieveInitPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/autoretrieve/init",
		AdminAutoretrieveInitPost,
	},

	Route{
		"AdminAutoretrieveListGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/autoretrieve/list",
		AdminAutoretrieveListGet,
	},

	Route{
		"AutoretrieveHeartbeatPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/autoretrieve/heartbeat",
		AutoretrieveHeartbeatPost,
	},

	Route{
		"CollectionsColuuidCommitPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/collections/{coluuid}/commit",
		CollectionsColuuidCommitPost,
	},

	Route{
		"CollectionsColuuidDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/collections/{coluuid}",
		CollectionsColuuidDelete,
	},

	Route{
		"CollectionsColuuidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/collections/{coluuid}",
		CollectionsColuuidGet,
	},

	Route{
		"CollectionsColuuidPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/collections/{coluuid}",
		CollectionsColuuidPost,
	},

	Route{
		"CollectionsFsAddPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/collections/fs/add",
		CollectionsFsAddPost,
	},

	Route{
		"CollectionsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/collections/",
		CollectionsGet,
	},

	Route{
		"CollectionsPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/collections/",
		CollectionsPost,
	},

	Route{
		"ContentAddCarPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/content/add-car",
		ContentAddCarPost,
	},

	Route{
		"ContentAddIpfsPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/content/add-ipfs",
		ContentAddIpfsPost,
	},

	Route{
		"ContentAddPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/content/add",
		ContentAddPost,
	},

	Route{
		"ContentAggregatedContentGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/aggregated/{content}",
		ContentAggregatedContentGet,
	},

	Route{
		"ContentAllDealsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/all-deals",
		ContentAllDealsGet,
	},

	Route{
		"ContentBwUsageContentGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/bw-usage/{content}",
		ContentBwUsageContentGet,
	},

	Route{
		"ContentCreatePost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/content/create",
		ContentCreatePost,
	},

	Route{
		"ContentDealsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/deals",
		ContentDealsGet,
	},

	Route{
		"ContentEnsureReplicationDatacidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/ensure-replication/{datacid}",
		ContentEnsureReplicationDatacidGet,
	},

	Route{
		"ContentFailuresContentGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/failures/{content}",
		ContentFailuresContentGet,
	},

	Route{
		"ContentImportdealPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/content/importdeal",
		ContentImportdealPost,
	},

	Route{
		"ContentListGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/list",
		ContentListGet,
	},

	Route{
		"ContentReadContGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/read/{cont}",
		ContentReadContGet,
	},

	Route{
		"ContentStagingZonesGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/staging-zones",
		ContentStagingZonesGet,
	},

	Route{
		"ContentStatsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/stats",
		ContentStatsGet,
	},

	Route{
		"ContentStatusIdGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/content/status/{id}",
		ContentStatusIdGet,
	},

	Route{
		"DealEstimatePost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/deal/estimate",
		DealEstimatePost,
	},

	Route{
		"DealInfoDealidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/info/{dealid}",
		DealInfoDealidGet,
	},

	Route{
		"DealProposalPropcidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/proposal/{propcid}",
		DealProposalPropcidGet,
	},

	Route{
		"DealQueryMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/query/{miner}",
		DealQueryMinerGet,
	},

	Route{
		"DealStatusByProposalPropcidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/status-by-proposal/{propcid}",
		DealStatusByProposalPropcidGet,
	},

	Route{
		"DealStatusMinerPropcidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/status/{miner}/{propcid}",
		DealStatusMinerPropcidGet,
	},

	Route{
		"DealTransferInProgressGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deal/transfer/in-progress",
		DealTransferInProgressGet,
	},

	Route{
		"DealTransferStatusPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/deal/transfer/status",
		DealTransferStatusPost,
	},

	Route{
		"DealsFailuresGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deals/failures",
		DealsFailuresGet,
	},

	Route{
		"DealsMakeMinerPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/deals/make/{miner}",
		DealsMakeMinerPost,
	},

	Route{
		"DealsStatusDealGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/deals/status/{deal}",
		DealsStatusDealGet,
	},

	Route{
		"PublicDealsFailuresGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/deals/failures",
		PublicDealsFailuresGet,
	},

	Route{
		"PublicMinersStorageQueryMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/storage/query/{miner}",
		PublicMinersStorageQueryMinerGet,
	},

	Route{
		"PublicMetricsDealsOnChainGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/metrics/deals-on-chain",
		PublicMetricsDealsOnChainGet,
	},

	Route{
		"PublicMinersDealsMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/deals/{miner}",
		PublicMinersDealsMinerGet,
	},

	Route{
		"PublicMinersStatsMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/stats/{miner}",
		PublicMinersStatsMinerGet,
	},

	Route{
		"NetAddrsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/net/addrs",
		NetAddrsGet,
	},

	Route{
		"PublicMinersFailuresMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/failures/{miner}",
		PublicMinersFailuresMinerGet,
	},

	Route{
		"PublicMinersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners",
		PublicMinersGet,
	},

	Route{
		"PublicNetAddrsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/net/addrs",
		PublicNetAddrsGet,
	},

	Route{
		"PublicNetPeersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/net/peers",
		PublicNetPeersGet,
	},

	Route{
		"AdminPeeringPeersDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersDelete,
	},

	Route{
		"AdminPeeringPeersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersGet,
	},

	Route{
		"AdminPeeringPeersPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersPost,
	},

	Route{
		"AdminPeeringStartPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/start",
		AdminPeeringStartPost,
	},

	Route{
		"AdminPeeringStatusGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/status",
		AdminPeeringStatusGet,
	},

	Route{
		"AdminPeeringStopPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/stop",
		AdminPeeringStopPost,
	},

	Route{
		"AdminPeeringPeersDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersDelete,
	},

	Route{
		"AdminPeeringPeersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersGet,
	},

	Route{
		"AdminPeeringPeersPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/peers",
		AdminPeeringPeersPost,
	},

	Route{
		"AdminPeeringStartPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/start",
		AdminPeeringStartPost,
	},

	Route{
		"AdminPeeringStatusGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/status",
		AdminPeeringStatusGet,
	},

	Route{
		"AdminPeeringStopPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/admin/peering/stop",
		AdminPeeringStopPost,
	},

	Route{
		"PinningPinsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/pinning/pins",
		PinningPinsGet,
	},

	Route{
		"PinningPinsPinidDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/pinning/pins/{pinid}",
		PinningPinsPinidDelete,
	},

	Route{
		"PinningPinsPinidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/pinning/pins/{pinid}",
		PinningPinsPinidGet,
	},

	Route{
		"PinningPinsPinidPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/pinning/pins/{pinid}",
		PinningPinsPinidPost,
	},

	Route{
		"PinningPinsPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/pinning/pins",
		PinningPinsPost,
	},

	Route{
		"PublicByCidCidGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/by-cid/{cid}",
		PublicByCidCidGet,
	},

	Route{
		"PublicInfoGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/info",
		PublicInfoGet,
	},

	Route{
		"PublicMetricsDealsOnChainGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/metrics/deals-on-chain",
		PublicMetricsDealsOnChainGet,
	},

	Route{
		"PublicMinersDealsMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/deals/{miner}",
		PublicMinersDealsMinerGet,
	},

	Route{
		"PublicMinersFailuresMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/failures/{miner}",
		PublicMinersFailuresMinerGet,
	},

	Route{
		"PublicMinersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners",
		PublicMinersGet,
	},

	Route{
		"PublicMinersStatsMinerGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/miners/stats/{miner}",
		PublicMinersStatsMinerGet,
	},

	Route{
		"PublicNetAddrsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/net/addrs",
		PublicNetAddrsGet,
	},

	Route{
		"PublicNetPeersGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/net/peers",
		PublicNetPeersGet,
	},

	Route{
		"PublicStatsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/public/stats",
		PublicStatsGet,
	},

	Route{
		"UserApiKeysGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/user/api-keys",
		UserApiKeysGet,
	},

	Route{
		"UserApiKeysKeyDelete",
		strings.ToUpper("Delete"),
		"/application-research/estuary/master/docs/swagger.json/user/api-keys/{key}",
		UserApiKeysKeyDelete,
	},

	Route{
		"UserApiKeysPost",
		strings.ToUpper("Post"),
		"/application-research/estuary/master/docs/swagger.json/user/api-keys",
		UserApiKeysPost,
	},

	Route{
		"UserExportGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/user/export",
		UserExportGet,
	},

	Route{
		"UserStatsGet",
		strings.ToUpper("Get"),
		"/application-research/estuary/master/docs/swagger.json/user/stats",
		UserStatsGet,
	},
}
