/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.http.*;
import io.micronaut.http.annotation.*;
import io.reactivex.Single;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.responses.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.MicronautCodegen", date = "2022-09-27T20:40:53.180766-10:00[Pacific/Honolulu]")
@Controller
public interface DealsApi {


    @Operation(summary = "Get storage failures for user", operationId = "dealsFailuresGet", description = "This endpoint returns a list of storage failures for user" , tags = {"deals"})
    @Get(value = "/deals/failures")
    default Single<HttpResponse<Void>> dealsFailuresGet() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Make Deal", operationId = "dealsMakeMinerPost", description = "This endpoint makes a deal for a given content and miner" , tags = {"deals"})
    @Post(value = "/deals/make/{miner}", consumes = {"*/*"})
    default Single<HttpResponse<Void>> dealsMakeMinerPost(@Parameter(description = "Deal Request") @Valid @Body String body
,@Parameter(description = "Miner") @PathVariable("miner") String miner
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get Deal Status", operationId = "dealsStatusDealGet", description = "This endpoint returns the status of a deal" , tags = {"deals"})
    @Get(value = "/deals/status/{deal}")
    default Single<HttpResponse<Void>> dealsStatusDealGet(@Parameter(description = "Deal ID") @PathVariable("deal") Integer deal
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }

}
