/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.UtilHttpError;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.http.*;
import io.micronaut.http.annotation.*;
import io.reactivex.Single;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.responses.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.MicronautCodegen", date = "2022-09-27T20:40:53.180766-10:00[Pacific/Honolulu]")
@Controller
public interface PinningApi {


    @Operation(summary = "List all pin status objects", operationId = "pinningPinsGet", description = "This endpoint lists all pin status objects" , tags = {"pinning"})
    @ApiResponse(responseCode = "400", description = "Bad Request")
    @ApiResponse(responseCode = "404", description = "Not Found")
    @ApiResponse(responseCode = "500", description = "Internal Server Error")
    @Get(value = "/pinning/pins", produces = { "application/json" })
    default Single<HttpResponse<Void>> pinningPinsGet() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Delete a pinned object", operationId = "pinningPinsPinidDelete", description = "This endpoint deletes a pinned object." , tags = {"pinning"})
    @Delete(value = "/pinning/pins/{pinid}")
    default Single<HttpResponse<Void>> pinningPinsPinidDelete(@Parameter(description = "Pin ID") @PathVariable("pinid") String pinid
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get a pin status object", operationId = "pinningPinsPinidGet", description = "This endpoint returns a pin status object." , tags = {"pinning"})
    @Get(value = "/pinning/pins/{pinid}")
    default Single<HttpResponse<Void>> pinningPinsPinidGet(@Parameter(description = "cid") @PathVariable("pinid") String pinid
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Replace a pinned object", operationId = "pinningPinsPinidPost", description = "This endpoint replaces a pinned object." , tags = {"pinning"})
    @Post(value = "/pinning/pins/{pinid}")
    default Single<HttpResponse<Void>> pinningPinsPinidPost(@Parameter(description = "Pin ID") @PathVariable("pinid") String pinid
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Add and pin object", operationId = "pinningPinsPost", description = "This endpoint adds a pin to the IPFS daemon." , tags = {"pinning"})
    @Post(value = "/pinning/pins")
    default Single<HttpResponse<Void>> pinningPinsPost(@Parameter(description = "cid") @PathVariable("cid") String cid
,@Parameter(description = "name") @PathVariable("name") String name
) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }

}
