//
// ContentAddBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ContentAddBody: Codable {


    /** File to upload */
    public var file: Data
    public init(file: Data) { 
        self.file = file
    }

}
