//
// MainUserStatsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct MainUserStatsResponse: Codable {


    public var numPins: Int?

    public var totalSize: Int?
    public init(numPins: Int? = nil, totalSize: Int? = nil) { 
        self.numPins = numPins
        self.totalSize = totalSize
    }

}
