//
// AutoretrieveAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class AutoretrieveAPI {
    /**
     Register autoretrieve server

     - parameter body: (body) Autoretrieve&#x27;s public key 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func adminAutoretrieveInitPost(body: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        adminAutoretrieveInitPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Register autoretrieve server
     - POST /admin/autoretrieve/init

     - API Key:
       - type: apiKey Authorization 
       - name: bearerAuth
     - parameter body: (body) Autoretrieve&#x27;s public key 

     - returns: RequestBuilder<Void> 
     */
    open class func adminAutoretrieveInitPostWithRequestBuilder(body: String) -> RequestBuilder<Void> {
        let path = "/admin/autoretrieve/init"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     List autoretrieve servers

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func adminAutoretrieveListGet(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        adminAutoretrieveListGetWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     List autoretrieve servers
     - GET /admin/autoretrieve/list

     - API Key:
       - type: apiKey Authorization 
       - name: bearerAuth

     - returns: RequestBuilder<Void> 
     */
    open class func adminAutoretrieveListGetWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/admin/autoretrieve/list"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Marks autoretrieve server as up

     - parameter token: (header) Autoretrieve&#x27;s auth token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func autoretrieveHeartbeatPost(token: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        autoretrieveHeartbeatPostWithRequestBuilder(token: token).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Marks autoretrieve server as up
     - POST /autoretrieve/heartbeat

     - API Key:
       - type: apiKey Authorization 
       - name: bearerAuth
     - parameter token: (header) Autoretrieve&#x27;s auth token 

     - returns: RequestBuilder<Void> 
     */
    open class func autoretrieveHeartbeatPostWithRequestBuilder(token: String) -> RequestBuilder<Void> {
        let path = "/autoretrieve/heartbeat"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "token": token
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
}
